# Generated by Django 2.2.4 on 2019-08-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Products_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('product_title', models.CharField(max_length=120)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_sku_data', models.CharField(max_length=1000)),
                ('is_th', models.IntegerField(blank=True, null=True)),
                ('is_tw', models.IntegerField(blank=True, null=True)),
                ('is_vn', models.IntegerField(blank=True, null=True)),
                ('is_my', models.IntegerField(blank=True, null=True)),
                ('is_ph', models.IntegerField(blank=True, null=True)),
                ('is_id', models.IntegerField(blank=True, null=True)),
                ('is_sg', models.IntegerField(blank=True, null=True)),
                ('data_source', models.CharField(max_length=1000)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_product',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ship_day', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_sku_number', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.CharField(blank=True, max_length=10, null=True)),
                ('img_url1', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url2', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url3', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url4', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url5', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url6', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url7', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url8', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_url9', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_source', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('api_push_status', models.BooleanField(default=False)),
                ('api_push_at', models.DateTimeField(blank=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_SKUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('sku_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sku_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=10, null=True)),
                ('img_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
